version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./_volumes/mongodb:/data/db

  # kitchenapp:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: kitchenapp
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - mongodb
